checks:
    php:
        code_rating: true
        duplication: true
filter:
    excluded_paths:
        - tests/*
build:
    environment:
        php:
            version: 7.2.4
    tests:
        override:
            -
                command: ./vendor/bin/phpunit --coverage-clover=coverage-file
                coverage:
                    file: coverage-file
                    format: php-clover
