language: php

php:
  - 7.2.4

services:
  - redis-server

before_script:
  - alias phpunit ./vendor/phpunit/phpunit/phpunit --bootstrap ./vendor/autoload.php ./tests/
  - composer install --dev

scripts:
  - ./vendor/phpunit/phpunit/phpunit --bootstrap ./vendor/autoload.php ./tests/ 
